jobs:
  include:
  - before_install:
    - echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt
      cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
    - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring
      /usr/share/keyrings/cloud.google.gpg add -
    - sudo apt-get update -y
    - sudo apt-get install google-cloud-sdk -y
    - sudo apt-get install kubectl -y
    - cd ./secrets/
    - openssl aes-256-cbc -K $encrypted_0d9f442b0df2_key -iv $encrypted_0d9f442b0df2_iv
      -in secrets.tar.enc -out secrets.tar -d && tar xvf secrets.tar
    env:
      global: CLOUDSDK_CORE_DISABLE_PROMPTS=1 CLOUDSDK_INSTALL_DIR=$HOME/google-cloud-sdk
    install:
    - pwd
    - ls
    - cd ..
    - pip install -r requirements.txt
    language: python
    os: linux
    python: 3.7
    script:
    - pwd
    - pytest -vs tests/app_schema/
    - pytest -vs tests/app_controllers/test_travis_controller.py
    - pytest -vs tests/app_controllers/test_clouddns_controller.py
    - pytest -vs tests/app_controllers/test_cloudrun_controller.py
    - pytest -vs tests/app_controllers/test_kubernetes_controller.py
    services:
    - docker
language: python
python:
- '3.7'
